# Generated by Django 4.2.15 on 2024-08-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=60)),
                ('project_short_desc', models.CharField(max_length=30)),
                ('project_desc', models.CharField(max_length=30)),
                ('project_image', models.ImageField(upload_to='projects/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
