# Generated by Django 4.2.15 on 2024-08-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMy', '0003_remove_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='categoryName',
        ),
    ]
