# Generated by Django 4.2.15 on 2024-10-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMy', '0004_rename_category_name_category_categoryname'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('is_live', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
