# Generated by Django 4.2.15 on 2024-10-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMy', '0006_card_is_live'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_live', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
